id: AE85D84E1
title: Maṇḍala Offering from Longsal Dorje Nyingpo
type: translation
pechas:
- I6BE655F6
- IDF8BDDBC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:00:56.017475
  last_modified_at: 2023-01-04 13:00:56.017494
  collections:
  - Longsal Nyingpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I6BE655F6/91D9: 78F7
  IDF8BDDBC/7A5D: 78F7
